language: python
python:
  - "3.7"
script:
  - python -m unittest discover -p "*_test.py"
install:
  - pip install codecov

script:
  - coverage run fraction_test.py
  - coverage run listutil_test.py  

after_success:
  - codecov
    
